throw warning when security check fails

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -89,8 +89,16 @@ jobs:
       - name: Lint container
         run: ./bin/console lint:container
 
-      - name: Check security
-        run: export PATH="$HOME/.symfony/bin:$PATH" ; symfony check:security
+      - name: Set up Symfony path
+        run: export PATH="$HOME/.symfony5/bin:$PATH"
+
+      - name: Check Symfony Security
+        id: security_check
+        run: symfony check:security || echo "::warning::Security check failed"
+
+      - name: Continue execution
+        if: ${{ steps.security_check.outcome == 'success' }}
+        run: echo "Security check succeeded"
 
       - name: Check doctrine mapping
         run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
